# Generated by Django 4.2.1 on 2023-09-20 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noteApi', '0002_remove_note_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='isDone',
            new_name='is_complete',
        ),
    ]
