# Generated by Django 4.2.1 on 2023-09-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteApi', '0003_rename_isdone_note_is_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='is_complete',
            field=models.BooleanField(),
        ),
    ]
