# Generated by Django 4.2.1 on 2023-09-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteApi', '0003_remove_note_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='isDone',
            field=models.BooleanField(default=False),
        ),
    ]
